#import ./TimelineItem.gql

fragment BlockTimeline  on blockTimeline_Entry {
  abstract
  id
  htmlContent
  timelineItems {
    ... on timelineItem_Entry {
      ...TimelineItem
    }
  }
  title
  typeHandle
  uid
}