#import ./ButtonLink.gql

fragment BlockListLinks on blockListLinks_Entry {
  abstract
  htmlContent
  linkItems {
    ...on linkItem_Entry {
      buttonLink {
        ...ButtonLink
      }
      description
    }
  }
  title
  typeHandle
  uid
}