fragment ButtonLink on LinkData {
  id
  element {
    ... on EntryInterface {
      title
      uri
    }
    ... on AssetInterface {
      title
      filename
      mimeType
    }
  }
  # newWindow
  title
  label
  defaultLabel
  type
  # typeLabel
  url
}