fragment ButtonLink on LinkData {
  ariaLabel
  defaultLabel
  entry {
    uri
  }
  label
  type
  url
  element {
    ... on EntryInterface {
      title
      slug
      uri
    }
    ... on AssetInterface {
      title
      filename
      mimeType
    }
  }
}