#import ./BlockHighlightedNews.gql
#import ./BlockHighlightedLinks.gql
#import ./BlockHighlightedServices.gql
#import ./BlockParagraph.gql
#import ./ImageFull.gql

fragment CompanyEntry on company_Entry {
  id
  companyBlocks {
    ... on blockHighlightedNews_Entry {
      ...BlockHighlightedNews
    }
    ... on blockHighlightedLinks_Entry {
      ...BlockHighlightedLinks
    }
    ... on blockHighlightedServices_Entry {
      ...BlockHighlightedServices
    }
    ... on blockParagraph_Entry {
      ...BlockParagraph
    }
  }
  metaTitle
  metaDescription
  ogImage {
    ... ImageFull
  }
  title
}