#import ./ButtonLink.gql
#import ./ImageFull.gql
#import ./PageBlocks.gql

fragment NewsEntry on news_Entry {
  buttonLink {
    ...ButtonLink
  }
  htmlContent
  id
  image {
    ...ImageFull
  }
  metaTitle
  metaDescription
  ogImage {
    ... ImageFull
  }
  title
  pageBlocks {
    ...PageBlocks
  }
}