#import ./ButtonLink.gql
#import ./ImageFull.gql 
#import ./NavigationLink.gql
#import ./PageBlocks.gql

fragment PagesEntry on pages_Entry {
  buttonLink {
    ...ButtonLink
  }
  dateUpdated
  htmlContent
  id
  metaTitle
  metaDescription
  ogImage {
    ... ImageFull
  }
  pageBlocks {
    ...PageBlocks
  }
  title
  withSidebar
  sidebarNavigation (level: 1) {
    ...NavigationLink
  }
  sidebarTitle
}