#import ./BlockAttachmentTable.gql
#import ./BlockContacts.gql
#import ./BlockGenericTable.gql
#import ./BlockMedia.gql
#import ./BlockParagraph.gql
#import ./BlockTimeline.gql
#import ./BlockListLinks.gql

fragment PageBlocks on pageBlocks_MatrixField {
  __typename
  ... on blockAttachmentTable_Entry {
    ...BlockAttachmentTable
  }
  ... on blockGenericTable_Entry {
    ...BlockGenericTable
  }
  ... on blockContacts_Entry {
    ...BlockContacts
  }
  ... on blockListLinks_Entry {
    ...BlockListLinks
  }
  ... on blockMedia_Entry {
    ...BlockMedia
  }
  ... on blockParagraph_Entry {
    ...BlockParagraph
  }
  ... on blockTimeline_Entry {
    ...BlockTimeline
  }
}