#import ./ButtonLink.gql
#import ./BlockContacts.gql
#import ./BlockParagraph.gql
#import ./BlockTimeline.gql

fragment ServicesEntry on services_Entry {
  abstract
  buttonLink {
    ...ButtonLink
  }
  id
  title
  pageBlocks {
    __typename
    ... on blockParagraph_Entry {
      ...BlockParagraph
    }
    ... on blockContacts_Entry {
      ...BlockContacts
    }
    ... on blockTimeline_Entry {
      ...BlockTimeline
    }
  }
}