#import ./CardServices.gql
#import ./ButtonLink.gql

fragment ServicesLauncherItem on servicesLauncher_Entry {
  abstract
  title
  serviceEntries {
    ... CardServices
  }
  buttonLink {
    ...ButtonLink
  }
}