#import ./ButtonLink.gql
#import ./ImageFull.gql 
#import ./PageBlocks.gql
#import ./Tag.gql

fragment ServicesEntry on services_Entry {
  buttonLink {
    ...ButtonLink
  }
  dateUpdated
  htmlContent
  id
  metaTitle
  metaDescription
  ogImage {
    ... ImageFull
  }
  pageBlocks {
    ...PageBlocks
  }
  tags {
    ...Tag
  }
  title
  withSidebar
}