#import ./ButtonLink.gql
#import ./ImageFull.gql 
#import ./NavigationLink.gql
#import ./PageBlocks.gql

fragment TransparenciesEntry on transparencies_Entry {
  buttonLink {
    ...ButtonLink
  }
  dateUpdated
  htmlContent
  id
  metaTitle
  metaDescription
  ogImage {
    ... ImageFull
  }
  pageBlocks {
    ...PageBlocks
  }
  parent {
    title
    uri
    parent {
      title
			uri
      parent {
        title
        uri
      }
    }
  }
  title
  withSidebar
  sidebarNavigation (level: 1) {
    ...NavigationLink
  }
  sidebarTitle
}