fragment NavigationLink on NodeInterface {
  children {
    id
    element {
      ... on EntryInterface {
        title
        uri
      }
      ... on AssetInterface {
        title
        filename
        mimeType
      }
    }
    newWindow
    title
    type
    typeLabel
    url
  }
  id
  element {
    ... on EntryInterface {
      title
      uri
    }
    ... on AssetInterface {
      title
      filename
      mimeType
    }
  }
  newWindow
  title
  type
  typeLabel
  url
  ... on mainNavigation_Node {
    secondary
    buttonStyle
  }
}

query GetNavigation($navHandle: String) {
  navigationNodes (navHandle: $navHandle, level: 1) {
    ...NavigationLink
  }
}