#import ./fragments/ImageFull.gql

query GetSEO {
  globalSet(handle: "seo") {
    ... on seo_GlobalSet {
      metaTitle
      metaDescription
      ogImage {
        ... ImageFull
      }
    }
  }
}