#import ./fragments/ButtonLink.gql
#import ./fragments/ImageFull.gql

query GetSocials {
  globalSet(handle: "socials") {
    ... on socials_GlobalSet {
      socialItems {
        ... on socialItem_Entry {
          title
          link_ {
            ... ButtonLink
          }
        }
      }
    }
  }
}