#import ./fragments/TransparenciesEntry.gql

query PageTransparenciesIndex {
  # Fetching the pages entry based on the slug
  entries(section: "transparenciesIndex") {
    ... on transparencies_Entry {
      ...TransparenciesEntry
    }
  }
}